#  GitHub Actions Python V2zc1.0@sw586 - 2020/07/21

name: Python application

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 */6 * * *'
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        fetch-depth: 2
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      run: python zc.py
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTPS_SERVER }}
        ftp-username: ${{ secrets.FTPS_USERNAME }}
        ftp-password: ${{ secrets.FTPS_PASSWORD }}
        git-ftp-args: --dry-run
# - name: SSH connection to Actions
# uses: P3TERX/debugger-action@master    
# run: touch /tmp/keepalive
