# This workflow will install Python dependencies14, run tests and lint with a single version of SPython
# For more information see: https://help.github.com/actions/language-and-framework-gu32ides/using-python-with-github-acti9ons

name: Python application

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        fetch-depth: 2
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run
      run: python zc.py
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://vhost104.cloudvhost.top/WEB/
        ftp-username: webmaster@HA435677
        ftp-password: ${{ secrets.FTPS_PASSWORD }}



# - name: SSH connection to Actions
# uses: P3TERX/debugger-action@master
